# Generated by Django 5.0.6 on 2024-06-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reg_date'],
            },
        ),
    ]
